General:
  Clock: clk
  Reset: rst
  ResetIsSync: 0
  ResetActiveLevel: 0
  Endianess: little
  IsByteIndividuallyAccesible: 0
Port:
UVM:
RTL:
  BusCSR: APB
Doc:
  Language: ru
  Format: asciidoc
  ImageDir: img
  ImageFormat: svg
  ImageQuality: 600dpi
  RegisterBitsOnTheLine: 16
RegisterMap:
  AddressUnit: word
Files:
  - registers.yaml
  - ports.yaml
